### ISSUE TITLE
Test - 人員資料 - 批次匯入 - 資料匯入失敗

### ISSUE THREAD

**Issue by yingtzuknst** [DoraKnst/estatemanageplatform#104]
**〔問題說明〕**
◆ Expect：
匯入資料格式正確、必填項目皆完成，可正常批次匯入

◆ Actual: 
匯入資料格式正確、必填項目皆完成，顯示資料匯入失敗

**〔測試步驟〕**
進入人員資料
點[新增-批次匯入]
[批次匯入測試資料.xls](https://drive.google.com/file/d/1kK_N2Arko5fx-yRc3XChtvgmhehHRrh2/view?usp=sharing)
資料匯入失敗
[匯入失敗訊息.png](https://drive.google.com/file/d/1OO9HoP0AS6PgZ4O-g44_-Lor9durRSdX/view?usp=sharing)

**〔功能/所在位置〕**
人員資料 - 新增 - 批次匯入

**〔重要性〕**
★★★

**〔備註〕**

**〔進案日期〕**
2018/11/23

**Comment by bcjohnblue** [comment]
我發現會有問題是因為 "工作性質"、"就職狀態的"部分，excel檔是用random的函式，所以才會顯示匯入失敗，我嘗試將第一筆人員的資料用下拉式選單設為 "正職"、"已離職"，將會顯示正常。

**Comment by yingtzuknst** [comment]
checked, fixed
