### ISSUE TITLE
測試機 - 公司帳戶管理 - 案場名單-未顯示所有新增案場名單

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#12]
**〔問題說明〕**
◆ Expect：
完成X家智生活[新增案場]後，智生活案場名單會新增X筆案場資訊，且狀態顯示為[申請新增中]

◆ Actual: 
完成X家智生活[新增案場]後，智生活案場名單會新增X筆案場資訊，且狀態顯示為[申請新增中]
另外5家案場並不會顯示在智生活案場名單上

**〔測試步驟〕**
登入物業雲管理後台
進入公司帳戶管理>蘋果物業>案場名單
依序新增案場：中友綠園邸、中華大樓、惠宇原山、東京市澀谷、竹城福和賞
智生活案場名單：只有顯示惠宇原山

**〔功能/所在位置〕**
公司帳戶管理/案場名單

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 
但該5筆新增案場申請都會顯示在變動申請的[處理中]列表裡

**〔進案日期〕**
2018/5/21

**Comment by monkey6366** [comment]
請明展確認API是否正確

**Comment by KnstMing** [comment]
API: /EstateManagement/Community/CommunityList 取得案場名單清單
已fix，請確認

**Comment by monkey6366** [comment]
確認OK

**Comment by DoraKnst** [comment]
@monkey6366  未修復

**Comment by KnstMing** [comment]
@WanYuKnst  已確認，這個為API問題。 6/14 完成調整，請驗測。

**Comment by DoraKnst** [comment]
checked,fixed
