### ISSUE TITLE
測試機 - 變動申請管理 - [處理中]、[已結單]列表資料排序調整

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#14]
**〔問題說明〕**
◆ Expect：
每次顯示10筆為一頁，由新到舊

◆ Actual: 
每次顯示10筆為一頁，由舊到新

**〔測試步驟〕**
進入物業雲管理後台
進入[變動申請管理]
檢視各筆資料排序方式

**〔功能/所在位置〕**
變動申請管理

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/5/21

**Comment by monkey6366** [comment]
這部分需要API這邊修正

**Comment by KnstMing** [comment]
@monkey6366  API排序已經改成由新到舊，請驗測

**Comment by DoraKnst** [comment]
Checked,done
