### ISSUE TITLE
測試機 - 公司帳戶管理 - 點擊[清除條件]無反應

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#16]
**〔問題說明〕**
◆ Expect：
點擊[清除條件]按鈕，會清除所有篩選條件內的內容變為空值

◆ Actual: 
點擊[清除條件]按鈕，無任何反應，並未清除個篩選條件已選擇的選項

**〔測試步驟〕**
登入物業雲管理後台
進入公司帳戶管理
點[公司]多選單→點選單中的全選按鈕
點查詢
顯示查詢結果
點[清除條件]>>無反應

**〔功能/所在位置〕**
公司帳戶管理

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/5/21

**Comment by DoraKnst** [comment]
@monkey6366  點擊[清除條件]按鈕，無任何反應，並未清除個篩選條件已選擇的選項

**Comment by DoraKnst** [comment]
@monkey6366 
進入公司帳戶管理：社區預設為全選
 點選[清除條件]
社區：打卡選單已全部取消勾選，但欄目仍顯示全選

**Comment by monkey6366** [comment]
已修正完成，6/20上測試

**Comment by DoraKnst** [comment]
checked,fixed
