### ISSUE TITLE
測試機 - 變動申請管理 - [社區]選單 勾選任意社區 造成該網頁當掉

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#19]
**〔問題說明〕**
◆ Expect：
點[社區]選單以勾選多個社區

◆ Actual: 
點[社區]選單>>該網頁當掉，點擊該網頁任何地方都無反應，必須重新整理該網頁，重新操作

**〔測試步驟〕**
進入變動申請管理
點[社區]選單
勾選任一社區
網頁當掉

**〔功能/所在位置〕**
變動申請管理

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/5/21

**Comment by DoraKnst** [comment]
未修復
測試 acer k50、asus GL553V 兩台筆電 -->  都當掉

**Comment by monkey6366** [comment]
請確認 chrome是否有啟用selenium IDE 套件，會影響到元件運作，關掉該套件即可正常運作

**Comment by DoraKnst** [comment]
@monkey6366  已移除selenium IDE 套件
可以成功勾選任意社區
但點擊[社區]選單的[全選] 卻會造成網頁當調

**Comment by monkey6366** [comment]
因社區選單數量多，耗時太長造成瀏覽器回應逾時訊息，但若要全選社區亦可透過全選物業公司取代，故建議拿掉社區全選的功能，已修正

**Comment by DoraKnst** [comment]
checked,fixed

**Comment by DoraKnst** [comment]
@monkey6366  變動申請 [已結單] 的社區選單未調整

**Comment by monkey6366** [comment]
已修正

**Comment by DoraKnst** [comment]
checked,fixed
