### ISSUE TITLE
測試機 - Side Menu 所有選項都用藍色框套色

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#2]
**〔問題說明〕**
◆ Expect：
只有所在位置的功能被選中套藍色
![1-](https://user-images.githubusercontent.com/35495325/40226484-5ac74900-5abe-11e8-8f1c-0af1ed30cb27.png)
![image](https://user-images.githubusercontent.com/35495325/40226530-7c3407ea-5abe-11e8-8f13-50dadd77d6fc.png)

◆ Actual: 
所有選項都用藍色框套色
**〔測試步驟〕**
登入物業帳號
進入[公司帳戶管理]或[變動申請管理]

**〔功能/所在位置〕**
物業雲管理後台

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 
**〔進案日期〕**

**Comment by monkey6366** [comment]
已修正完成20180521

**Comment by DoraKnst** [comment]
checked,done
