### ISSUE TITLE
測試機 - 公司帳戶管理 -變動申請：勾選項目以外的選下勾選框未灰階掉

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#20]
**〔問題說明〕**
◆ Expect：
變動申請-智生活：
勾選[申請延長串接]時[申請解除串接]的勾選框會被灰階且無法勾選

◆ Actual: 
變動申請-智生活：
勾選[申請延長串接]時[申請解除串接]的勾選框無法勾選>>但未灰階

**〔測試步驟〕**
進入公司帳戶管理
進入Kingnet公司>>進入[案場名單]
點社區"松仁富邑]該筆資訊的[變動申請]按鈕
勾選[申請延長串接]
[申請解除串接]的勾選框未灰階

**〔功能/所在位置〕**
公司帳戶管理/案場名單

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/5/21

**Comment by monkey6366** [comment]
元件因素，需花時間確認

**Comment by DoraKnst** [comment]
暫時Wonfix
功能性：勾選一個，另一個無法勾選-->有
