### ISSUE TITLE
測試機-公司帳戶管理-案場名單-變動申請:必填欄位未設定為必填

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#21]
〔問題說明〕
◆ Expect：
申請日期、案場名稱、選擇申請項目、選擇串接時間、合約上傳 皆為必填

◆ Actual:
申請日期、合約上傳 並非必填，沒有填資料也可成功送出該申請

〔測試步驟〕
登入物業雲管理後台
進入公司帳戶管理>Kingnet公司>案場名單
點"泰盛大樓"的變動申請
只輸入：[申請延長串接]、延長日期
點[確定]
成功送出

〔功能/所在位置〕
公司帳戶管理/案場名單

〔重要性〕
★★★

〔備註〕
@monkey6366
變動申請管理/處理中 列表上該筆申請會自動帶入：該筆申請當天的日期作為[申請日期]

〔進案日期〕
2018/5/21

**Comment by monkey6366** [comment]
修改完成

**Comment by DoraKnst** [comment]
@monkey6366 
申請日期、合約上傳 並非必填，沒有填資料也可成功送出該申請

**Comment by DoraKnst** [comment]
checked,fixed
