### ISSUE TITLE
測試機 - 公司帳戶管理 - 變動申請、新增案場>申請日期：沒顯示當日日期

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#22]
**〔問題說明〕**
◆ Expect：
新增案場>>新增日期：自動帶入當天日期顯示
變動申請>>申請日期：自動帶入當天日期顯示

◆ Actual: 
新增案場>>新增日期：沒有自動帶入當天日期顯示
變動申請>>申請日期：沒有自動帶入當天日期顯示

**〔測試步驟〕**
1. 進入公司帳戶管理
2. 點[新增案場] 或 [變動申請]
3. 檢視彈窗內的:
    4. 新增案場>>新增日期 >>沒顯示當日日期
    5. 變動申請>>申請日期>>沒顯示當日日期

**〔功能/所在位置〕**
公司帳戶管理

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/5/21

**Comment by monkey6366** [comment]
修改完成

**Comment by DoraKnst** [comment]
@monkey6366 
新增案場>>新增日期：沒有自動帶入當天日期顯示
變動申請>>申請日期：沒有自動帶入當天日期顯示

**Comment by DoraKnst** [comment]
checked,fixed
