### ISSUE TITLE
測試機 - 公司帳戶管理 - 資料預設規則調整&篩選欄位顯示內容修正

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#24]
〔問題說明〕
◆ Expect：
進入該頁面的預設狀態為：
篩選欄位：[地區]、[公司] 選單為全選
資料顯示：該篩選結果的前10筆
◆ Actual:
進入該頁面的預設狀態為：

篩選欄未{地區、物業公司} 皆為空值
資料顯示：排序方式無法辨認
※不合哩，若篩選欄位皆為空值：就不應該撈的到資料，篩選欄位應該顯示：所撈取的資料是根據什麼篩選規則

〔測試步驟〕
進入公司帳戶管理
檢視該列表 篩選欄位、資料顯示

〔功能/所在位置〕
公司帳戶管理

〔重要性〕
★★★

〔備註〕
@monkey6366

〔進案日期〕
2018/5/21

**Comment by monkey6366** [comment]
已修改完成

**Comment by DoraKnst** [comment]
Checked,pass
地區沒有全選
