### ISSUE TITLE
測試機 - 公司帳戶管理 - 案場名單 按鈕顏色變更

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#25]
**〔問題說明〕**
按鈕顏色調整：請調整如下圖所示
![1- 3](https://user-images.githubusercontent.com/35495325/40301603-2a33184c-5d1f-11e8-87f0-d0c12206a722.png)

**〔測試步驟〕**
進入公司帳戶管理>Kingnet公司
檢視[智生活案場名單]

**〔功能/所在位置〕**
公司帳戶管理

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/5/21

**Comment by monkey6366** [comment]
修改完成

**Comment by DoraKnst** [comment]
checked,done
