### ISSUE TITLE
測試機 - 變動申請管理 - 小婉瑜 [主管]權限已開，但並未顯示[同意][拒絕]功能供使用

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#26]
**〔問題說明〕**
◆ Expect：
點擊任一筆[處理中]的變動申請單：
於該筆申請單中>顯示[同意]、[拒絕]按鈕
且可以[同意]、[拒絕]變動申請單

◆ Actual: 
點擊任一筆[處理中]的變動申請單：
於該筆申請單中>沒有顯示[同意]、[拒絕]按鈕
且無法[同意]、[拒絕]變動申請單

**〔測試步驟〕**
進入變動申請管理>處理中
點任一變動申請單
檢視該變動申請單的內容
未顯示[同意]、[拒絕]供使用

**〔功能/所在位置〕**
變動申請管理

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/5/21

**Comment by monkey6366** [comment]
已修改完成

**Comment by DoraKnst** [comment]
@monkey6366  未修復
![image](https://user-images.githubusercontent.com/35495325/40756977-c34791fc-64b8-11e8-8108-94fe2b9566e5.png)

**Comment by monkey6366** [comment]
與明展對過，目前偏向是API的問題，已請明展協助處理

**Comment by KnstMing** [comment]
API 已fix，請確認

**Comment by DoraKnst** [comment]
checked,fixed
確認是否確實新增、延長、解除串接需待V2.0前台上線後連動 方可驗證
