### ISSUE TITLE
公司帳戶管理-案場名單-移除[縣市]、[鄉鎮]欄位，新增[地址]欄位

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#30]
調整內容：
1.智生活案場
[縣市]、[鄉鎮]欄位移除
新增[地址]欄位

2.其他案場
[縣市]、[鄉鎮]欄位移除
新增[地址]欄位
**〔功能/所在位置〕**
公司帳戶管理-案場名單

更改後：(如下圖)
![1- _](https://user-images.githubusercontent.com/35495325/40539638-eebcbe5e-6047-11e8-87e8-86c2832dbd01.png)

更改前：(如下圖)
![00- _](https://user-images.githubusercontent.com/35495325/40539707-37286756-6048-11e8-9299-fc4b57b93ff1.png)

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 
新版Wireframe 會jandi @monkey6366 @KnstMing 
**〔進案日期〕**
2018/5/25

**Comment by KnstMing** [comment]
05/30 13:50已上測試機
調整API-/EstateManagement/Community/CommunityList 取得案場名單清單
其他案場名單，OutPut Params 增加地址欄位(Address)
前端部份，請 @monkey6366 接手處理

**Comment by monkey6366** [comment]
修改完成

**Comment by DoraKnst** [comment]
@monkey6366  地址欄目有新增，縣市、鄉鎮欄目已刪除，但欄目標題未變更
Expect：編號、案場名稱、地址、狀態、功能
Actual：便號、案場名稱、縣市、鄉鎮市區、狀態功能 (如下圖)
![image](https://user-images.githubusercontent.com/35495325/41134405-cc351f86-6afe-11e8-8c3f-871bd18247e1.png)

**Comment by DoraKnst** [comment]
checked,fixed
