### ISSUE TITLE
測試機 - 變動申請管理 - [申請失敗]標記和下方文字相黏

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#31]
**〔問題說明〕**
◆ Expect：
[申請失敗]標記和下方文字相隔一段間距(如下圖)
![image](https://user-images.githubusercontent.com/35495325/41134627-e921e646-6aff-11e8-82c3-ca513b95f737.png)

◆ Actual: 
[申請失敗]標記和下方文字相黏(如下圖)
![image](https://user-images.githubusercontent.com/35495325/41134596-becb25ba-6aff-11e8-94bf-4855e8c07e89.png)

**〔測試步驟〕**
進入變動申請管理
點擊任一則[處理中]的變動申請單
檢視右上方 [申請失敗]標記和下方文字
 [申請失敗]標記和下方文字相黏

**〔功能/所在位置〕**
變動申請管理

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/06/08

**Comment by monkey6366** [comment]
已修正，6/20上系統

**Comment by DoraKnst** [comment]
checked,fixed
