### ISSUE TITLE
公司帳戶管理 - 新增案場 - 帶入前一筆新增的資料

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#32]
**〔問題說明〕**
◆ Expect：
[新增案場] 新增一案場後再點[新增案場] 新增第二個案場
[新增案場-智生活] 所有欄位皆為預設值

◆ Actual: 
[新增案場] 新增一案場後再點[新增案場] 新增第二個案場
[新增案場-智生活] ：案場名稱、合約上傳-->帶入了前一筆的資料

**〔測試步驟〕**
進入公司帳戶管理
點Kingnet公司
新增案場"達麗首席"
新增成公
再新增一間案場
點[新增案場]按鈕
跳出[新增案場-智生活]彈窗
檢視[案場名稱]、[合約上傳]欄位-->帶入了新增案場"達麗首席"的資料

**〔功能/所在位置〕**
公司帳戶管理 - 新增案場

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/06/08

**Comment by monkey6366** [comment]
已修正，6/20前上測試

**Comment by DoraKnst** [comment]
checked,fixed
