### ISSUE TITLE
測試機 - 公司帳戶管理 - 新增案場 案場名稱選擇 不能以關鍵字輸入搜尋

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#33]
**〔問題說明〕**
◆ Expect：
- 新增案場 案場名稱選擇 可以以關鍵字輸入搜尋 (如下圖，截圖Wireframe)
![image](https://user-images.githubusercontent.com/35495325/41137706-3b14789c-6b0f-11e8-9884-31c23650e041.png)

◆ Actual: 
- 新增案場 案場名稱選擇 不能以關鍵字輸入搜尋 (如下圖)
![image](https://user-images.githubusercontent.com/35495325/41137715-4a4c4a7e-6b0f-11e8-8c82-f636e6e85bcd.png)

**〔測試步驟〕**
新增一間案場
點[新增案場]按鈕
跳出[新增案場-智生活]彈窗
點擊[案場名稱]選單
無法輸入關鍵字搜尋案場

**〔功能/所在位置〕**
公司帳戶管理 - 新增案場

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/06/08

**Comment by monkey6366** [comment]
已修正 6/20上測試

**Comment by DoraKnst** [comment]
checked,fixed
