### ISSUE TITLE
測試機 - 公司帳戶管理/案場名單 - 同意[解除串接]，解除日未到，案場已於名單中移除

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#34]
**〔問題說明〕**
前置條件：
社區A串接日期(6/8-6/10)  
申請[解除串接] 於6/9 解除
主管[同意]該筆申請

◆ Expect：
若解除日未到(6/9之前)Ex.6/8：社區A 仍在案場名單裡
若解除日當單、之後(6/9、6/9之後)：社區A 仍在解除記錄裡，於案場名單中移除

◆ Actual: 
若解除日未到(6/9之前)Ex.6/8：社區A 已於案場名單中移除

**〔測試步驟〕**
進入公司帳戶管理/天天保全/案場名單
替社區"麗緻昱瑭"申請解除串接於6/9

進入變動申請管理/[麗緻昱瑭"申請解除串接]申請單
點擊[同意]

回到公司帳戶管理/天天保全/案場名單 --->麗緻昱瑭 已從案場名單中移除

**〔功能/所在位置〕**
 公司帳戶管理/案場名單

**〔重要性〕**
★★★

**〔備註〕**
@KnstMing 

**〔進案日期〕**
2018/06/08

**Comment by KnstMing** [comment]
@monkey6366  在麻煩Front-End 協助調整 [新增解除申請單] call API 傳入Params裡的Start(起始日)、Due(迄日)都傳入[畫面UI的解除日]。API:/EstateManagement/Community/AddCommunityDetail
建立 案場名單申請記錄 新增案場/延長串接/解除串接

**Comment by monkey6366** [comment]
測試正常 6/19上測試

**Comment by DoraKnst** [comment]
@KnstMing  無法測試
因為無法提出 [解除串接]申請
會跳出如下提視窗
![image](https://user-images.githubusercontent.com/35495325/41456654-c19efe06-70b3-11e8-9b2f-f281a3e529fd.png)

**Comment by DoraKnst** [comment]
checked,fixed
