### ISSUE TITLE
測試機 - 公司帳戶管理/案場名單 - 同意[延長串接]，案場卻從案場名單中移除

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#35]
〔問題說明〕
前置條件：
社區A串接日期(6/8-6/22)
申請[延長串接] 延長至6/30

◆ Expect：
案場名單中：社區A { 狀態[已串接] ；串接資訊：延長串接、申請成功}

◆ Actual:
社區A從案場名單中移除

〔測試步驟〕
進入公司帳戶管理/天天保全/案場名單
替社區"大東興"申請延長至6/30

進入變動申請管理/
至6/30
解除入變動申請管理/[大東興"申請延長串接]申請單
點擊[同意]

回到公司帳戶管理/天天保全/案場名單 --->大東興 已從案場名單中移除

〔功能/所在位置〕
公司帳戶管理/案場名單

〔重要性〕
★★★

〔備註〕
@KnstMing

〔進案日期〕
2018/06/08

**Comment by KnstMing** [comment]
@monkey6366  在麻煩Front-End 協助調整 [新增延長申請單] call API 傳入Params裡的Start(起始日)、Due(迄日)都傳入[畫面UI的延長日期]。API:/EstateManagement/Community/AddCommunityDetail
建立 案場名單申請記錄 新增案場/延長串接/解除串接

**Comment by monkey6366** [comment]
已修正，測試kingnet -> 高雄宜居 2018/7/31 -> 2018/8/31
6/20上測試

**Comment by DoraKnst** [comment]
checked,fixed
