### ISSUE TITLE
測試機 - 公司帳戶管理 - 新增案場/案場選單中 出現[申請中]、[已串接]社區

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#37]
**〔問題說明〕**
◆ Expect：
新增案場/案場選單中 不會出現[申請中]、[已串接]社區

◆ Actual: 
新增案場/案場選單中 出現[申請中]、[已串接]社區

**〔測試步驟〕**
狀況1：
前置條件：物業公司A 申請串接社區K
進入公司帳戶管理-物業公司B
點擊[新增案場]>點開[案場名稱]選單>看見社區K在選單中供選擇 (社區K不應出現)

狀況2：
前置條件：物業公司A 正已串接社區K
進入公司帳戶管理-物業公司B
點擊[新增案場]>點開[案場名稱]選單>看見社區K在選單中供選擇 (社區K不應出現)

**〔功能/所在位置〕**
公司帳戶管理 - 新增案場/案場選單中

**〔重要性〕**
★★★

**〔備註〕**
@KnstMing 

**〔進案日期〕**
2018/06/08

**Comment by DoraKnst** [comment]
目標：避免重複串接 已串接案場、申請中案場
--

> @KnstMing @monkey6366  請協助配合調整

**原方案：**
篩選[案場名稱]選單，不出現已串接案場、申請中案場
執行難點：不同期間：選單篩選結果不同

**新方案：**
不篩選[案場名稱]選單

在使用者完成[案場名稱]、[串接時間]等資料填寫後，點[送出]時檢核

【情境1】

若 該社區所申請的串接期間：

	已被其他物業公司串接

則 跳出提視窗說"申請新增失敗，因該案場已被其他物業公司串接"

【情境2】

若 該社區所申請的串接期間：

	已被其他物業公司提出申請新增串接

則 跳出提視窗說"申請新增失敗，因該案場已被其他物業公司申請串接"

**Comment by KnstMing** [comment]
API完成調整 6/14上測試機，請 @monkey6366 ，接繼處理

**Comment by monkey6366** [comment]
後臺前端已修正OK,6/20前上測試

**Comment by DoraKnst** [comment]
checked,fixed

**Comment by DoraKnst** [comment]
@KnstMing   bug又出現了，未修復

**Comment by DoraKnst** [comment]
重現使用物業公司、社區

社區：國雄馥花園

物業公司：葡萄物業
申請串接：2018/07/11 至 2018/07/31
申請日期：7/11
@KnstMing 
物業公司：AppleOne
申請串接2018/07/12 至 2018/07/30
申請日期：7/12

**Comment by KnstMing** [comment]
測試問題，API已修正，請重新驗測。 @WanYuKnst

**Comment by DoraKnst** [comment]
checked,fixed
