### ISSUE TITLE
測試機 - 公司帳戶管理/案場名單 - [新增案場]新增申請被拒絕，該案場進入解除記錄

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#38]
**〔問題說明〕**
物業公司A 申請新增社區K 被拒絕
◆ Expect：
該案場不在物業公司 案場名單中，且不在解除記錄中

◆ Actual: 
該案場不在物業公司 案場名單中，**但在解除記錄中**

**〔測試步驟〕**
進入公司帳戶管理/天天保全/案場名單
新增案場[太子景雲見]--> [新增案場]申請單建立(申請單編號：180608028)

進入變動申請管理
點擊申請單編號：180608028
拒絕該筆申請

進入公司帳戶管理/天天保全/案場名單
不在名單中，卻在解除記錄 (不應該出現在解除記錄)

**〔功能/所在位置〕**
公司帳戶管理/案場名單

**〔重要性〕**
★★★

**〔備註〕**
@KnstMing 

**〔進案日期〕**
2018/06/08

**Comment by KnstMing** [comment]
@monkey6366  在麻煩Front-End 協助調整 [新增解除申請單] call API 傳入Params裡的Start(起始日)、Due(迄日)都傳入[畫面UI的解除日]。API:/EstateManagement/Community/AddCommunityDetail
建立 案場名單申請記錄 新增案場/延長串接/解除串接

**Comment by monkey6366** [comment]
>已與明展確認，應該是API的問題

**Comment by KnstMing** [comment]
已修正 6/14上測試機，請驗測

**Comment by monkey6366** [comment]
6/19上測試機

**Comment by DoraKnst** [comment]
checked,fixed
