### ISSUE TITLE
變動申請管理 - [解除串接]申請單 解除生效日該條目未顯示

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#39]
**〔問題說明〕**
◆ Expect：
顯示：文字"解除生效日" + 日期 (如圖)
![default](https://user-images.githubusercontent.com/35495325/41150439-96ba20d0-6b40-11e8-9e29-133032462637.PNG)

◆ Actual: 
顯示：文字"申請串接時接" [原本串接結束日期]至 [申請解除串接日期](如下圖)
![image](https://user-images.githubusercontent.com/35495325/41150607-08610bfe-6b41-11e8-8626-72d656386bfc.png)

**〔測試步驟〕**
進入變動申請管理
點擊 任一筆[解除串接]申請
檢視 解除日期 該列

**〔功能/所在位置〕**
變動申請管理

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/06/08

**Comment by monkey6366** [comment]
6/13修正，預計6/19上測試

**Comment by DoraKnst** [comment]
checked,fixed
