### ISSUE TITLE
測試機 - 公司帳戶管理/案場名單 - 智生活案場名單 新增"已通過-等待串接"

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#40]
**〔新增項目說明〕**
◆ Expect：
假設今天為2018/6/11
甲物業公司 欲新增社區A，申請通過，但串皆時間尚未到，該案場在[案場名單]的狀態顯示為"已通過-等待串接"

**範例：**
6/11 申請新增串接社區A，串接期間 8/1-8/30
6/11 送出申請，尚未審核 狀態：申請新增中
6/11-6/14狀態：申請新增中
6/15 申請通過 -->狀態：已通過-等待串接
6/15-7/31-->狀態：已通過-等待串接
8/1-8/30-->狀態：已串

**〔功能/所在位置〕**
公司帳戶管理/案場名單

**〔重要性〕**
★★★

**〔備註〕**
@KnstMing 

**〔進案日期〕*
2018/06/11

**Comment by KnstMing** [comment]
API完成調整 6/14上測試機，請驗測

**Comment by DoraKnst** [comment]
checked,fixed
