### ISSUE TITLE
測試機 - 管理者選單 - 建立

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#41]
**〔需求項目〕**
開通下列人員有權限在物業雲管理後台
審核 [同意]、[拒絕] 變動申請書

1. 吳宥溱 
2. 廖敏傑 
3. 連國泰 
4. 林建清 
5. 李嘉裕 
6. 朱建嘉 
7. 周煥強
8. 林子皓
9. 洪婉瑜
10. 陳羿臻

**〔功能/所在位置〕**
物業雲 管理後台

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/06/15

**Comment by KnstMing** [comment]
測試區-審核變動申請書 權限已開。
SSO User ID 如下：
吳宥溱	681
廖敏傑	519
連國泰	485
林建清	582
李嘉裕	510
朱建嘉	484
周煥強	493
林子皓	486
洪婉瑜	491
陳羿臻	680

**Comment by DoraKnst** [comment]
checked,done
