### ISSUE TITLE
測試機 - 解除串接 文案調整

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#43]
**〔問題說明〕**
◆ Expect：
在公司帳戶管理/案場名單/提出[變動申請]提視窗內容：改為"串接截止日"(標題) ；"串接最後一天"(輸入框提示文字) #如下圖
![1-6 7](https://user-images.githubusercontent.com/35495325/41463328-9e89c436-70c8-11e8-9148-5877e00e950a.png)

在變動申請管理：改為"串接截止日" #如下圖
![1-6 8](https://user-images.githubusercontent.com/35495325/41463351-b42f00da-70c8-11e8-85e0-7ffc20e91177.png)

**〔功能/所在位置〕**
公司帳戶管理/案場名單
變動申請管理

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366  配合解除串接計算邏輯調整

**〔進案日期〕**
2018/6/15

**Comment by KnstMing** [comment]
API 申請解除串接，申請截止日期未在[案場串接期間]，已調整錯誤訊息文案

**Comment by monkey6366** [comment]
頁面已修正

**Comment by DoraKnst** [comment]
@monkey6366  @KnstMing  在變動申請管理：改為"串接截止日" #如下圖 未調整

**Comment by DoraKnst** [comment]
@monkey6366 公司帳戶管理 案場名單 "解除記錄" 改為 "串接截止日"
![image](https://user-images.githubusercontent.com/35495325/41753570-cdaf6b8e-7600-11e8-811c-36ab89425ef2.png)

**Comment by monkey6366** [comment]
已修改

**Comment by DoraKnst** [comment]
@monkey6366  下述未修改 在變動申請管理："解除串接"申請單的"解除串接日(排定)" 改為"串接截止日" #如下圖
Expect
![1-6 8](https://user-images.githubusercontent.com/35495325/41463351-b42f00da-70c8-11e8-85e0-7ffc20e91177.png)

Actual
![image](https://user-images.githubusercontent.com/35495325/42297652-8c585a5a-8033-11e8-9608-626e931428c1.png)

**Comment by monkey6366** [comment]
修改完成

**Comment by WanYuKnst** [comment]
@monkey6366  並未修正

**Comment by DoraKnst** [comment]
checked,fixed
