### ISSUE TITLE
測試機 - 新增回到EIP首頁的按鈕

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#44]
**〔新需求〕**
點擊頁面右上角Menu Icon 顯示[EIP首頁]的選項-->點擊後開啟新頁面導致[EIP首頁] 
(https://eip.kingnetsmart.com.tw)
如下圖
![1-6 8 1](https://user-images.githubusercontent.com/35495325/41755380-9e1cbe40-7609-11e8-855c-b6b8eef6f2d8.png)

**〔功能/所在位置〕**
所有物業雲管理後台頁面

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/06/22

**Comment by monkey6366** [comment]
已修正

**Comment by DoraKnst** [comment]
checked,fixed
