### ISSUE TITLE
測試機 - 公司帳戶管理/人員編制 - 重設密碼 失敗

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#46]
**〔問題說明〕**
◆ Expect：
可以重設人員密碼

◆ Actual: 
重設人員密碼失敗
如下圖
![image](https://user-images.githubusercontent.com/35495325/42299394-80e726b0-803d-11e8-83f9-20f5c446ba9f.png)

**〔測試步驟〕**
進入Kingnet公司帳戶/人員編制
點擊"測試帳號1b"的重設密碼
點[確定]
跳出"無權執行此操作彈窗

**〔功能/所在位置〕**
公司帳戶管理/人員編制

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/07/05

**Comment by DoraKnst** [comment]
@monkey6366  未修復
重設密碼後，至物業雲前台
重新用新密碼登入>>無法登入
用舊密碼登入>>成功登入

**Comment by monkey6366** [comment]
因新增管理者時uid帶成所有者，造成已修復完成

**Comment by DoraKnst** [comment]
checked,fixed
