### ISSUE TITLE
測試機 - 變動申請管理 - 申請書中 社區名稱消失

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#47]
**〔問題說明〕**
◆ Expect：
會顯示社區名稱

◆ Actual: 
![image](https://user-images.githubusercontent.com/35495325/42667760-eae8661c-867f-11e8-8714-0a62ac26fe24.png)

**〔測試步驟〕**
進入變動申請管理
在處理中或已結單點任一申請書

**〔功能/所在位置〕**
變動申請管理/處理中或已結單

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2015/07/13

**Comment by monkey6366** [comment]
已針對API改版修正完成

**Comment by DoraKnst** [comment]
checked,fixed
