### ISSUE TITLE
測試機 - 變動申請管理 - [處理中]申請書點[返回]跳轉回[變動申請管理-已結單]頁面

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#48]
**〔問題說明〕**
◆ Expect：
[處理中]申請書點[返回]跳轉回[變動申請管理-**處理中**]頁面

◆ Actual: 
[處理中]申請書點[返回]跳轉回[變動申請管理-**已結單**]頁面

**〔測試步驟〕**
登入 wanyuhungu
進入[變動申請管理]
點 [180716002]申請書
進入[180716002]申請書 詳細資訊
點返回-->跳轉回[變動申請管理-已結單]頁面

**〔功能/所在位置〕**
變動申請管理

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/07/16

**Comment by monkey6366** [comment]
已修正

**Comment by DoraKnst** [comment]
checked,fixed
