### ISSUE TITLE
Demo - 公司帳戶管理/案場名單 - 新增智生活案場 失敗

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#49]
**〔問題說明〕**
◆ Expect：
可以新增智生活案場

◆ Actual: 
無法成功新增智生活案場

**〔測試步驟〕**
如下圖
![20180719_141333](https://user-images.githubusercontent.com/35495325/42924764-3f840bbc-8b5e-11e8-84c9-077e7ec84a78.gif)

**〔功能/所在位置〕**
公司帳戶管理/案場名單

**〔重要性〕**
★★★

**〔備註〕**
@KnstMing 

**〔進案日期〕**
2018/07/19

**Comment by KnstMing** [comment]
發生問題是因為使用正式DB Function沒有權限，導致執行失敗。已請至越協助開放權限，解決問題。請重新測試

**Comment by DoraKnst** [comment]
checked,fixed
