### ISSUE TITLE
Test & Demo - 變動申請管理/處理中 & 已結單 - 縣市篩選失敗

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#50]
**〔問題說明〕**
◆ Expect：
可以透過縣市篩選申請單

◆ Actual: 
無法透過縣市篩選申請單

**〔測試步驟〕**
進入Test 或Demo站台的變動申請管理
篩選台中市
點查詢
無反應(並不會篩處社區屬於台中市的申請書)

**〔功能/所在位置〕**
變動申請管理/處理中

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/07/20

**Comment by DoraKnst** [comment]
@monkey6366 checked,fixed
請上Demo

**Comment by KnstMing** [comment]
API配合調整，已上Demo機

**Comment by DoraKnst** [comment]
Checked, fixed
