### ISSUE TITLE
測試機 - 變動申請管理 - 同意、拒絕 新增案場失敗

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#51]
**〔問題說明〕**
◆ Expect：
主管可以[同意]、[拒絕]變動申請書
[同意]、[拒絕]後該筆申請單會轉至[已結單]並從[處理中]消失

◆ Actual: 
主管可以[同意]、[拒絕]變動申請書
[同意]、[拒絕]後該筆申請單並未轉至[已結單]
仍顯示於[處理中]列表
**〔測試步驟〕**
進入Test的物業雲管理後台 / 變動申請管理
點擊任一筆[處理中]的申請書
點擊[同意]>跳出成功審核提視窗>跳轉回[處理中]列表 > 該筆申請書仍在
點擊[拒絕]>跳出成功審核提視窗>跳轉回[已結單]列表 >未顯示該筆申請書，該筆申請書仍在[處理中]列表

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 
Demo沒有此問題
之前測試Test站台的後台也無此問題

**〔進案日期〕**
2018/07/20

**Comment by DoraKnst** [comment]
@KnstMing 想請問預計何時完成修復?

**Comment by KnstMing** [comment]
@WanYuKnst  已排除問題

**Comment by DoraKnst** [comment]
@KnstMing  未修復，仍無法成功新增

**Comment by DoraKnst** [comment]
checked,fixed

**Comment by DoraKnst** [comment]
@KnstMing @monkey6366  問題重現 請確認
使用帳號：wanyuhungu
位置：物業雲測是站台
步驟：某社區申請己除串接
進入變動申請管理>點[拒絕]或[同意]接無效>無法成功審核通過該筆申請

**Comment by KnstMing** [comment]
變動申請管理 [拒絕]或[同意]，審核動作寫在DB層，
測試DB每天早上會由正式DB restore，
審核動作DB部份沒能正常restore過來，因此審核會有問題
