### ISSUE TITLE
Test & Demo -  變動申請管理 - 點擊[處理中]或[已結單]的申請書>進入失敗

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#52]
**〔問題說明〕**
◆ Expect：
在變動申請管理 
點擊[處理中]或[已結單]的任一筆申請書
可以進入查看申請書

◆ Actual: 
在變動申請管理 
點擊[處理中]或[已結單]的任一筆申請書
空白頁面 一直跑圈圈

**〔測試步驟〕**
以wanyuhungu帳號登入
進入變動申請管理 
點擊[處理中]或[已結單]的任一筆申請書
檢視申請書

**〔功能/所在位置〕**
變動申請管理

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 test和demo站台都有此問題

**〔進案日期〕**
2018/07/25

**Comment by monkey6366** [comment]
已修正完成

**Comment by DoraKnst** [comment]
checked,fixed
