### ISSUE TITLE
測試機 -  後臺新增 登出按鈕

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#56]
**〔問題說明〕**
◆ Expect：
![1- 1](https://user-images.githubusercontent.com/35495325/45340801-a5886200-b5ca-11e8-90f8-c74f8d5d4da9.png)

◆ Actual: 
![1-](https://user-images.githubusercontent.com/35495325/45340817-afaa6080-b5ca-11e8-9d23-0897530b17c9.png)

**〔測試步驟〕**
登入物業雲後台
試圖登出，無登出按鈕

**〔功能/所在位置〕**
 登出按鈕

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/09/11

**Comment by monkey6366** [comment]
已修改完成，放於右上角回EIP下面

**Comment by DoraKnst** [comment]
check, done
