### ISSUE TITLE
Test - 社區意見反映 - 匯出彈窗文案未調整為"匯出"

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#58]
**〔問題說明〕**
◆ Expect：
匯出彈窗文案調整為"匯出"

◆ Actual: 
匯出彈窗文案未為"匯出公告"

**〔測試步驟〕**
進入意見反映
匯出PDF、Excel
檢視匯出彈窗標題文字

**〔功能/所在位置〕**
社區意見反映

**〔重要性〕**
★★★

**〔備註〕**

**〔進案日期〕**
2018/10/11

**Comment by bcjohnblue** [comment]
10/16 fixed.

**Comment by DoraKnst** [comment]
2018/10/17 checked, fixed
