### ISSUE TITLE
Test - 人員差勤 - 無照片提示文案 字型調整

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#59]
**〔問題說明〕**
◆ Expect：
字型：微軟正黑體

◆ Actual: 
字型：新細明體

**〔測試步驟〕**
進入人員差勤 
檢視一筆無照片的差勤紀錄

**〔功能/所在位置〕**
人員差勤

**〔重要性〕**
★★★

**〔備註〕**

**〔進案日期〕**
2018/10/11

**Comment by bcjohnblue** [comment]
10/16 fixed.

**Comment by DoraKnst** [comment]
2018/10/17 checked, fixed
