### ISSUE TITLE
Test - 前台 - 新增社區公告 - 未修復[日其覆蓋問題]

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#60]
**〔問題說明〕**
◆ Expect：
在選擇日期時過去選擇過去[日期紀錄選]單不會顯示並遮蔽[日期選單]

◆ Actual: 
過去[日期紀錄選]單會顯示並遮蔽[日期選單]
![image](https://user-images.githubusercontent.com/35495325/46779468-7fc9b680-cd4a-11e8-8c1a-320e56a566e4.png)

**〔測試步驟〕**
進入社區公告/新增公告
刊登日期設定
發現 過去[日期紀錄選]單不會顯示並遮蔽[日期選單]

**〔功能/所在位置〕**
社區公告/新增公告

**〔重要性〕**
★★★

**〔備註〕**
@KnstMing 

**〔進案日期〕**
2018/10/11

**Comment by bcjohnblue** [comment]
10/16 fixed.

**Comment by DoraKnst** [comment]
2018/10/17 checked, fixed
