### ISSUE TITLE
Test- 前台 - 通知 - 社區名稱 未調整為粗體

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#61]
**〔問題說明〕**
◆ Expect：
通知文案中的社區名稱 調整為粗體

◆ Actual: 
通知文案中的社區名稱 未調整為粗體
![image](https://user-images.githubusercontent.com/35495325/46779578-08485700-cd4b-11e8-9f4e-4a4e365343a3.png)

**〔測試步驟〕**
登入 ec_owner-ectest
打卡通知列表檢視

**〔功能/所在位置〕**
通知

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 

**〔進案日期〕**
2018/10/11

**Comment by KnstMing** [comment]
@WanYuKnst  舊的通知訊息，無法將社區名稱 改為粗體。此功能只能為V2.1新的通知才有
