### ISSUE TITLE
Test- 個人戶管理 - 視窗寬度沒有配合文案長度自動調整寬度

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#62]
**〔問題說明〕**
◆ Expect：
此為V2.0 正式機 畫面
![image](https://user-images.githubusercontent.com/35495325/46779715-91f82480-cd4b-11e8-82a5-0dbeb3404698.png)

◆ Actual: 
此為V2.1 測試機 畫面
![image](https://user-images.githubusercontent.com/35495325/46779677-72f99280-cd4b-11e8-83d7-3488709f9c50.png)

**〔測試步驟〕**
進入 個人戶管理
編輯Email 設一個很的email
發現如上圖Expect 文字跑出視窗的問題

**〔功能/所在位置〕**
個人戶管理

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 

**〔進案日期〕**
20181011

**Comment by bcjohnblue** [comment]
10/16 fixed.

**Comment by DoraKnst** [comment]
2018/10/17 checked, fixed
