### ISSUE TITLE
Test - 前台 - 全公司公告、個別案場公告 - 匯出未顯示匯出視窗

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#63]
**〔問題說明〕**
◆ Expect：
全公司公告、個別案場公 - 匯出會顯示匯出視窗 提示下載進度

◆ Actual: 
全公司公告、個別案場公 - 匯出未顯示匯出視窗
點擊[匯出]後會直接下載檔案

**〔測試步驟〕**
進入 全公司公告、個別案場公告
篩選出一些公告紀錄
點匯出PDF或Excel
會直接下載檔案

**〔功能/所在位置〕**
 全公司公告、個別案場公告  | 匯出功能

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue  匯出彈窗的標題請一同從"匯出公告"調整文案為"匯出"

**〔進案日期〕**
20181011

**Comment by bcjohnblue** [comment]
10/16 fixed.

**Comment by DoraKnst** [comment]
2018/10/17 Checked, fixed
