### ISSUE TITLE
Test - 前台 - 巡邏 - 無資料點[匯出pdf] 顯示 Server Error畫面

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#64]
**〔問題說明〕**
◆ Expect：
 無資料點[匯出PDF]>>停留在原畫面
![expect](https://user-images.githubusercontent.com/35495325/46781886-52830580-cd56-11e8-96bf-179453b5037f.gif)

◆ Actual: 
 無資料點[匯出]>>顯示 Server Error畫面
![actual](https://user-images.githubusercontent.com/35495325/46781894-5d3d9a80-cd56-11e8-8a85-470d035d2134.gif)

**〔測試步驟〕**
進入 巡邏
點[匯出-pdf]
顯示如下圖
![image](https://user-images.githubusercontent.com/35495325/46781924-80684a00-cd56-11e8-8c90-722b95401d05.png)

**〔功能/所在位置〕**
巡邏

**〔重要性〕**
★★★

**〔備註〕**
巡邏 [匯出-excel] >>停留在原畫面
其他有匯出功能的功能Ex.社區公告、意見反映，在無撈取資料下點匯出>>會停留在原畫面

**〔進案日期〕**
2018/10/11

**Comment by bcjohnblue** [comment]
10/16 fixed.

**Comment by DoraKnst** [comment]
@bcjohnblue  未修復
**〔問題說明〕**
◆ Expect：
如V1.0上線版
https://drive.google.com/file/d/1aXYU3p95NBr990yDfdQavl6e0cN3eHJF/view?usp=sharing
◆ Actual: 
如V2.1 Test
https://drive.google.com/file/d/1lB7TM3RYEI8QKROJt8M-x0JWgeDSKKmr/view?usp=sharing

**〔測試步驟〕**
初始進入某功能→點匯出PDF→顯示Server Error頁面
初始進入某功能→點匯出Excel→下載Excel檔→打開Excel檔顯示"<meta http-equiv=Content-Type content=text/html;charset=utf-8><style> .textmode { mso-number-format:\@; } </style>"



**〔功能/所在位置〕**
社區公告、社區意見反映、巡邏、人員差勤、全公司公告、個別案場公告

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue  未修復

**〔進案日期〕**
2018/10/17

**Comment by bcjohnblue** [comment]
10/18 fixed.

**Comment by DoraKnst** [comment]
1019 checked fixed
