### ISSUE TITLE
Test - 後台 - 公司帳戶管理 說明文案調整

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#65]
**〔問題說明〕**
◆ 調整內容：
改為
![image](https://user-images.githubusercontent.com/35495325/46782159-b2c67700-cd57-11e8-90db-6882d252aad3.png)

◆ Actual: 
![image](https://user-images.githubusercontent.com/35495325/46782168-c40f8380-cd57-11e8-8c71-161cdf6f814d.png)

**〔測試步驟〕**
進入[ 公司帳戶管理]
檢視說明文案

**〔功能/所在位置〕**
公司帳戶管理 

**〔重要性〕**
★★★

**〔備註〕**
此為Wireframe文案顯示錯誤導致，請協助調整
白板已調整

**〔進案日期〕**

**Comment by bcjohnblue** [comment]
10/16 fixed.

**Comment by DoraKnst** [comment]
2018/10/17 check, fixed
