### ISSUE TITLE
後台 - 登出顯示錯誤畫面

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#66]
**〔問題說明〕**
◆ Expect：
點[登出]會跳回物業雲後台SSO登入畫面

◆ Actual: 
點[登出]顯示如下畫面
![image](https://user-images.githubusercontent.com/35495325/46782909-a7c11600-cd5a-11e8-9acc-11da83d6d43e.png)

**〔測試步驟〕**
用wanyuhungu帳號登入 物業雲後台
點右上角[登出]按鈕
顯示如上畫面

**〔功能/所在位置〕**
登出

**〔重要性〕**
★★★

**〔備註〕**

**〔進案日期〕**
2018/10/11

**Comment by bcjohnblue** [comment]
10/16 fixed.

**Comment by DoraKnst** [comment]
2018/10/17 check, fixed
