### ISSUE TITLE
後台 - 公司帳戶管理 - 登入後首次點某公司帳號顯示[提示彈窗]

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#67]
**〔問題說明〕**
◆ Expect：
登入後首次點某公司帳號不會顯示[提示彈窗]

◆ Actual: 
登入後首次點某公司帳號顯示[提示彈窗] 如下圖
![image](https://user-images.githubusercontent.com/35495325/46782985-fa9acd80-cd5a-11e8-9702-1f29c96de24b.png)

**〔測試步驟〕**
登入物業雲後台
進入[公司帳戶管理]
點"EC測試公司"
顯示如上圖

**〔功能/所在位置〕**
公司帳戶管理

**〔重要性〕**
★★★

**〔備註〕**
視窗點[確定]可以順利進入該公司帳號檢視詳細資訊
接著返回公司帳戶表在在點選進入其他帳號不會再顯示上圖提視窗

**〔進案日期〕**
20181011

**Comment by bcjohnblue** [comment]
10/16 fixed.

**Comment by DoraKnst** [comment]
2018/10/17 check, fixed
