### ISSUE TITLE
後台 - 變動申請管理 - 點[匯出]未顯示匯出進度提視窗

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#68]
**〔問題說明〕**
◆ Expect：
點[匯出]應顯示匯出進度提視窗
請參考白板Wireframe

◆ Actual: 
點[匯出]未顯示匯出進度提視窗
**〔測試步驟〕**

**〔功能/所在位置〕**
變動申請管理 處理中、已結單

**〔重要性〕**
★★★

**〔備註〕**

**〔進案日期〕**
20181011

**Comment by bcjohnblue** [comment]
10/16 fixed.

**Comment by DoraKnst** [comment]
2018/10/17 check, fixed
