### ISSUE TITLE
Test - 後台 - 變動申請管理 - [縣市查詢]功能撈取資料失敗

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#69]
**〔問題說明〕**
◆ Expect：
 [縣市查詢]功能撈取資料可以確實撈取符合條件的紀錄

◆ Actual: 
 [縣市查詢]功能撈取資料失敗
**〔測試步驟〕**
如操作影片
https://drive.google.com/file/d/1e94YxZNAl5m4S1PWg44Xp1ZxvToXaJAD/view?usp=sharing

**〔功能/所在位置〕**
進入 變動申請管理 處理中、已結單
顯示選擇"台中"  應要顯示"遠雄之星" (遠雄之星2 為位於台中市的社區)

**〔重要性〕**
★★★

**〔備註〕**

**〔進案日期〕**
2018/10/11

**Comment by bcjohnblue** [comment]
10/16 fixed.

**Comment by DoraKnst** [comment]
2018/10/17 check, fixed
