### ISSUE TITLE
測試機 - 公司帳戶管理 - [新增人員] 失敗

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#7]
**〔問題說明〕**
◆ Expect：
可以成功[新增人員]

◆ Actual: 
[新增人員]失敗，挑除彈窗顯示"error :[object Object]" (如下圖)
![image](https://user-images.githubusercontent.com/35495325/40228181-219c6c50-5ac3-11e8-8c8c-50bf7827a683.png)

**〔測試步驟〕**
登入物業雲管理後台
進入[公司帳戶管理]
點[天天保全]
進入[天天保全]基本資訊頁面
點[人員編制]
進入[人員編制]
點[新增成員]

**〔功能/所在位置〕**
公司帳戶管理/人員編制

**〔重要性〕**
★★★

**〔備註〕**
@monkey6366 

**〔進案日期〕**
2018/5/18

**Comment by DoraKnst** [comment]
@monkey6366 
其他公司帳戶新建人員>>成功
天天保全、壓測公司新建人員>>失敗 (出現如下圖提示)
![image](https://user-images.githubusercontent.com/35495325/40756501-888b0adc-64b6-11e8-9ea7-1cfb8e618144.png)

(公司建立時未建立所有者的公司帳戶，後來才建立所有者的公司，新增人員都會失敗)

**Comment by monkey6366** [comment]
對接oauths問題已排除

**Comment by DoraKnst** [comment]
@monkey6366  未修復

天天保全：新增人員失敗，顯示如下圖提視窗 "此帳號不屬於任何群組"
![image](https://user-images.githubusercontent.com/35495325/41456437-085b80d6-70b3-11e8-9a9a-c1308aeac84c.png)

蘋果物業：新增人員失敗，顯示如下圖提視窗 ："選擇的帳號不是superAccount"

![image](https://user-images.githubusercontent.com/35495325/41456491-312195be-70b3-11e8-8f8b-1897d53e4ee2.png)

**Comment by monkey6366** [comment]
建議新建一個務業公司重新測試，因之前建立之公司的管理者在oauths上未分群組，oauths調整後這些帳號就無法建立自己公司的使用者，所以要用新的公司建立的管理者再測

**Comment by DoraKnst** [comment]
checked,fixed
