### ISSUE TITLE
Test - 後台 - 變動申請管理 - 出現未預期提示窗，且[社區縣市]、[社區查詢]、[物業公司查詢]被禁用

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#70]
**〔問題說明〕**
◆ Expect：
不會出現未預期提示窗，篩選功能不會被禁用
除非情境是：
使用物業公司查詢時>>社區查詢、社區縣市篩選 會被禁用
使用社區查詢、社區縣市篩選>>物業公司查詢 會被禁用

◆ Actual: 
如操作測試影片所示
https://drive.google.com/file/d/1oRWjQgjooarxg7esHyjDEcu65tdjDbVW/view?usp=sharing

**〔測試步驟〕**
進入 變動申請管理
點擊[日期

**〔功能/所在位置〕**
變動申請管理 處理中、已結單

**〔重要性〕**
★★★

**〔備註〕**
並非每次登入使用都會發生此問題
目前測試登出後重新登入會發生此問題是次數是：4次 (總共測試5次) 

**〔進案日期〕**

**Comment by bcjohnblue** [comment]
我進去的時候沒有出現這個問題，目前不知道為什麼會有這個狀況，可能要再觀察.

**Comment by DoraKnst** [comment]
@bcjohnblue  問題再次重現
繼續觀察

![image](https://user-images.githubusercontent.com/35495325/47199338-ad92a900-d3a3-11e8-95a1-7f3a96f969cf.png)

選項禁用-測試影片
https://drive.google.com/file/d/1wUcWyz1Qzi_HAN6g7CFUIJY4wTWgkxtL/view?usp=sharing

**Comment by bcjohnblue** [comment]
10/19 fixed.

**Comment by bcjohnblue** [comment]
我後來好像找到問題在哪了. 目前已經修復完畢 再請婉瑜測看看. 如果有問題的話再跟我說 謝謝

**Comment by bcjohnblue** [comment]
我後來好像找到問題在哪了. 目前已經修復完畢 再請婉瑜測看看. 如果有問題的話再跟我說 謝謝

**Comment by DoraKnst** [comment]
10/22 checked, fixed
