### ISSUE TITLE
Test - 管理報表 - 匯出未顯示 匯出進度提視窗

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#71]
〔問題說明〕
◆ Expect：
點[匯出]應顯示匯出進度提視窗
請參考白板Wireframe

◆ Actual:
點[匯出]未顯示匯出進度提視窗
〔測試步驟〕

〔功能/所在位置〕
管理報表

〔重要性〕
★★★

〔備註〕

〔進案日期〕
20181011

**Comment by bcjohnblue** [comment]
10/16 fixed.

**Comment by DoraKnst** [comment]
2018/10/17 check, fixed
