### ISSUE TITLE
Test - 公司內部公告 - 標籤功能 載入失敗、無法新增

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#72]
**〔問題說明〕**
◆ Expect：
檢視公告列表時：透過公告列表標籤欄位可以查詢已建立之標籤
新增公告時：標籤欄位>1.可以查詢已建立之標籤；2.新增新標籤

◆ Actual: 
檢視公告列表時：透過公告列表標籤欄位查詢→顯示" 載入失敗"
新增公告時：標籤欄位>1.可以查詢已建立之標籤→顯示" 載入失敗"；2.新增新標籤→顯示" 載入失敗"
![image](https://user-images.githubusercontent.com/35495325/47060139-f2c9a600-d1fe-11e8-8936-4845d5c0d50c.png)

![image](https://user-images.githubusercontent.com/35495325/47060124-dfb6d600-d1fe-11e8-9ff3-8888f540605a.png)

**〔測試步驟〕**
進入公司內部公告：全公司公告、個別案場公告
透過公告列表標籤欄位可以查詢已建立之標籤→顯示" 載入失敗"
新增公告時：標籤欄位>1.可以查詢已建立之標籤→顯示" 載入失敗"；2.新增新標籤→顯示" 載入失敗"

**〔功能/所在位置〕**
全公司公告、個別案場公告

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 

**〔進案日期〕**
2018/10/17

**Comment by bcjohnblue** [comment]
10/17 fixed.

**Comment by DoraKnst** [comment]
1019 checked fixed
