### ISSUE TITLE
Test - 後台- 未修復[日其覆蓋問題] 

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#73]
〔問題說明〕
◆ Expect：
在選擇日期時[日期選單] 不會 被[過去選用紀錄清單]遮蔽

◆ Actual:
在選擇日期時[日期選單] 會 被[過去選用紀錄清單]遮蔽

〔測試步驟〕
使用有日期選單功能的主功能>>[日期選單]被遮蔽 (如下圖)
![image](https://user-images.githubusercontent.com/35495325/47060552-aaab8300-d200-11e8-92aa-24cf7e8ab2ab.png)
![image](https://user-images.githubusercontent.com/35495325/47060554-ada67380-d200-11e8-8eb7-d6d729d96603.png)

〔功能/所在位置〕
社區公告/新增公告

〔重要性〕
★★★

〔備註〕
@bcjohnblue 

〔進案日期〕
2018/10/11

**Comment by bcjohnblue** [comment]
10/17 fixed.

**Comment by DoraKnst** [comment]
1019 checked, fixed
