### ISSUE TITLE
Test - 前台 - 資料異動按鈕框線消失

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#75]
**〔問題說明〕**
◆ Expect：
按鈕有框線 色號：#66666 (已更新至白板)
![image](https://user-images.githubusercontent.com/35495325/47128589-700b1e80-d2c4-11e8-89e0-f8d0522f5875.png)

◆ Actual: 
![image](https://user-images.githubusercontent.com/35495325/47128398-97152080-d2c3-11e8-804a-bd082d91fc57.png)

**〔測試步驟〕**
登入ec_owner-ectest
進入人員資料
檢視異動按鈕[改卡]、[詳細]

**〔功能/所在位置〕**
人員資料

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 

**〔進案日期〕**
2018/10/18

**Comment by bcjohnblue** [comment]
10/18 fixed.

**Comment by DoraKnst** [comment]
checked, fixed 10/19
