### ISSUE TITLE
Demo,Test - 意見反映、人員差勤 - 匯出失敗

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#76]
**〔問題說明〕**
◆ Expect：
可以成功匯出PDF、Excel

◆ Actual: 
匯出PDF、Excel失敗(如下圖)
意見反映
![image](https://user-images.githubusercontent.com/35495325/47329831-ac65c280-d6a8-11e8-8e40-9a7ac3e46a78.png)

人員差勤
![image](https://user-images.githubusercontent.com/35495325/47329838-b25ba380-d6a8-11e8-9611-06e368b9cb65.png)

**〔測試步驟〕**
登入estatetest1-kingnet.net
進入意見反映/、人員差勤 - /
輸入篩選期間 8/1~10/23
點查詢
點匯出PDF 或 Excel
匯出失敗

**〔功能/所在位置〕**
意見反映、人員差勤

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue @KnstMing 
Demo、Test 的意見反映、人員差勤皆匯出PDF、Excel失敗
公告、巡邏 可成功匯出
上週測試Test無此問題

**〔進案日期〕**
2018/10/23

**Comment by bcjohnblue** [comment]
10/24 fixed.

**Comment by DoraKnst** [comment]
10/24 checked, fixed
