### ISSUE TITLE
Demo,Test - 人員差勤 - 匯出 文案未調整

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#77]
**〔問題說明〕**
◆ Expect：
匯出視窗標題文案為 "匯出"

◆ Actual: 
匯出視窗標題文案為 "匯出公告"

**〔測試步驟〕**
登入estatetest1-kingnet.net
進入 人員差勤 
輸入篩選期間 8/1~10/23
點查詢
點匯出PDF 或 Excel
顯示匯出視窗 顯示標題文案為"匯出公告"
顯示匯出失敗彈窗

**〔功能/所在位置〕**
人員差勤

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 
Demo、Test 皆有此問題

**〔進案日期〕**
2018/10/23

**Comment by bcjohnblue** [comment]
10/24 fixed.

**Comment by DoraKnst** [comment]
10/24 checked, fixed
