### ISSUE TITLE
Test - 人員資料 - 批次匯入失敗

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#82]
**〔問題說明〕**
◆ Expect：
若資料格式正確可已成功批次匯入

◆ Actual: 
若資料格式正確>>仍無法成功批次匯入

**〔測試步驟〕**
登入estatetest1-kingnet.net
進入 人員資料
下載模板Excel
打開Excel模板輸入資料並儲存檔案
進入 人員資料
點[批次匯入]
顯示匯入格是錯誤(如下圖)
![image](https://user-images.githubusercontent.com/35495325/47337402-5273f580-d6c6-11e8-9b90-b06787563188.png)

匯入檔案：
https://drive.google.com/file/d/1FdPDSJiAdbOSTK7Hc5cIrVNtCWiYN5BR/view?usp=sharing

**〔功能/所在位置〕**
人員資料/ 批次匯入

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 

**〔進案日期〕**
2018/10/23

**Comment by bcjohnblue** [comment]
10/25 fixed.

**Comment by DoraKnst** [comment]
1026 checked,fixed
