### ISSUE TITLE
Test - 人員資料 - [部門]、[職務]選單 未填寫資料選像文案調整

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#83]
**〔問題說明〕**
◆ Adjust：
使用人員資料列表[部門]、[職務]篩選功能時
針對[部門]、[職務]欄位 未填寫內容的人員資料
選項名稱改為 "未填寫"

◆ Actual: 
針對[部門]、[職務]欄位 未填寫內容的人員資料
選項為 (如下圖) 空白
![image](https://user-images.githubusercontent.com/35495325/47337663-7d127e00-d6c7-11e8-8267-b46c212df421.png)

**〔測試步驟〕**
進入 人員資料
檢視  [部門]、[職務]篩選功能
顯示如上圖

**〔功能/所在位置〕**
人員資料

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue  已調整在白板上

**〔進案日期〕**
2018/10/23

**Comment by DoraKnst** [comment]
@bcjohnblue 
![image](https://user-images.githubusercontent.com/35495325/47343754-71c84e00-d6d9-11e8-94ff-93f8ba1581dc.png)
列表內容協同調整

**Comment by bcjohnblue** [comment]
10/24 fixed.

**Comment by DoraKnst** [comment]
2018/10/29：bcjohnblue 已調整 [未填寫]選項 在 部門、職務 篩選單 固定為排序最後的選項

**Comment by DoraKnst** [comment]
2018/10/30 Checked, fixed
