### ISSUE TITLE
Test - 人員資料 - 模板資料格式調整

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#86]
**【調整項目】**

Num | 欄位 | 調整內容
-- | -- | --
1 | 出生年月日 | 資料格式設定：日期,     Ex. 2018/10/18
2 | 到職日 | 資料格式設定：日期,    Ex.  2018/10/18
3 | 聯絡電話1 | 資料格式設定：文字,     避免輸入首個值為"0"時被移除
4 | 聯絡電話2 | 資料格式設定：文字,     避免輸入首個值為"0"時被移除
5 | 聯絡電話3 | 資料格式設定：文字,     避免輸入首個值為"0"時被移除
6 | 緊急聯絡人姓名1     電話 | 資料格式設定：文字,     避免輸入首個值為"0"時被移除
7 | 緊急聯絡人姓名2     電話 | 資料格式設定：文字 ,    避免輸入首個值為"0"時被移除
8 | 卡片編號 | 資料格式設定：文字,     避免輸入首個值為"0"時被移除

範本檔案：
https://drive.google.com/file/d/13ATqOsYOguK1WE2GoIov_Tz6GvSa9dyW/view?usp=sharing

**〔功能/所在位置〕**
人員資料

**〔重要性〕**
★★★

**〔備註〕**
@KnstMing 

**〔進案日期〕**
2018/10/24

**Comment by bcjohnblue** [comment]
10/24 人員資料excel公版下載已更新成上面的範本檔案.

**Comment by DoraKnst** [comment]
@bcjohnblue  2018/10/29 checked,fixed
最新公版的版本為 #98 上的連結
