### ISSUE TITLE
Test, Demo, 正式 - 人員管理 - 新增人員 按鈕失效

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#87]
**〔問題說明〕**
◆ Expect：
新增人員 可以成空新增

◆ Actual: 
新增人員 按鈕失效

**〔測試步驟〕**
登入estatetest1-kingnet.net
進入人員管理
新增人員
點[確認]按鈕沒有反應 >>無法成功新增人員

**〔功能/所在位置〕**
人員管理 

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 

**〔進案日期〕**
2018/10/24

**Comment by KnstMing** [comment]
@WanYuKnst  測試機已fix，請複驗，謝謝

**Comment by DoraKnst** [comment]
@bcjohnblue 
公司帳號顯示錯誤
![image](https://user-images.githubusercontent.com/35495325/47415956-37c57d80-d7a7-11e8-8bb3-5c0e2985d9a2.png)

**Comment by KnstMing** [comment]
@WanYuKnst  建立帳號的時候，傳錯帳號資料，導致建帳號有問題。請測試建新帳號是否還有此問題

**Comment by DoraKnst** [comment]
@KnstMing 還是有唷
![image](https://user-images.githubusercontent.com/35495325/47418562-ee782c80-d7ac-11e8-9b5a-f1ca068e1002.png)

**Comment by DoraKnst** [comment]
@KnstMing checked, fixed
