### ISSUE TITLE
Test - 人員資料 - 下載[匯入模板] 名稱錯誤

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#88]
**〔問題說明〕**
◆ Expect：
下載模板之檔案名稱為
物業雲_人員資料批次匯入範本01

◆ Actual: 
下載模板之檔案名稱為
物業雲V3.0 人事資料_匯入模板ForXls

**〔測試步驟〕**
登入ec_owner-ectest
進入 人員資料
點 新增-Excel公版下載
檢視下在的檔案之名稱

**〔功能/所在位置〕**
 人員資料

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 

**〔進案日期〕**
2018/10/25

**Comment by bcjohnblue** [comment]
10/25 fixed.

**Comment by DoraKnst** [comment]
1029 checked,fixed
