### ISSUE TITLE
Test - 人員資料 - 感應卡登記-若為中文輸入法會無法成功登記

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#89]
**〔問題說明〕**
◆ Expect：
目前輸入法：中、英、或其他任何輸入法下
皆可成功登記感應卡 (前提式此感應卡尚未被登記過)

◆ Actual: 
目前輸入法：英文→可成功登記感應卡 (前提式此感應卡尚未被登記過)
目前輸入法：中文→登記失敗感應卡 (前提式此感應卡尚未被登記過)

**〔測試步驟〕**

>情境A
前置設定：中文輸入法
登入ec_owner-ectest
進入 人員資料
點任一筆資料的[改卡]、[開卡]
無法成功登記，停留在原感應卡感應畫面

>情境B
前置設定：中文輸入法
登入ec_owner-ectest
進入 人員資料
點新增單筆人員資料
進入新增人員頁面
點[登記]卡片按鈕
無法成功登記，停留在原感應卡感應畫面

>情境C
前置設定：中文輸入法
登入ec_owner-ectest
進入 人員資料
點任一筆人員資料的[詳細]
進入人員詳細資料頁面
點編輯
進入人員資料編輯頁面
點[登記]或[改卡]卡片按鈕
無法成功登記，停留在原感應卡感應畫面

**〔功能/所在位置〕**
人員資料列表、新增人員資料頁、編輯人員資料頁

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 

**〔進案日期〕**
2018/10/25

**Comment by bcjohnblue** [comment]
10/25 fixed.

**Comment by DoraKnst** [comment]
@bcjohnblue  10/29 測試：
中文輸入法下可已成功登記感應卡、更改感應卡，但會跳出[瀏覽器 更新密碼彈窗]
![image](https://user-images.githubusercontent.com/35495325/47625236-de6e9d00-db5e-11e8-9386-8a33ca159cee.png)

Q: 有辦法調整成不跳出[瀏覽器 更新密碼彈窗]嗎?

**Comment by bcjohnblue** [comment]
10/29 有再調整過. 但是不確定是否可以不跳出[瀏覽器 更新密碼彈窗].  麻煩@WanYuKnst 之後再測看看.

**Comment by DoraKnst** [comment]
還是會跳出耶，請協助評估是否可以調整，若無法請告知~

**Comment by bcjohnblue** [comment]
現在chrome瀏覽器都設定輸入密碼的話一定會跳出[更新密碼彈窗]，目前找不到有效的方法禁止瀏覽器的行為.

**Comment by DoraKnst** [comment]
checked, fixed
