### ISSUE TITLE
Test - 人員資料 - 新增/編輯 人員資料 -  若有填寫緊急連絡人-姓名、電話未填寫提示文案調整

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#91]
**〔問題說明〕**
◆ Expect：
若有填寫緊急連絡人-姓名、電話未填寫提示文案調整
提示文案為：請填寫完整資訊

◆ Actual: 
若有填寫緊急連絡人-姓名、電話未填寫提示文案調整
提示文案為：請輸入數值

**〔測試步驟〕**
登入ec_owner-ectest
進入 人員資料
新增人員資料 / 編輯人員資料
緊急連絡人{姓名有填，電話未填}或{姓名未填，電話有填}
顯示錯誤提示 (如上圖)

**〔功能/所在位置〕**
人員資料 - 新增/編輯 人員資料

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 
已更新置白板，關鍵字查詢：issue#91

**〔進案日期〕**
2018/10/25

**Comment by bcjohnblue** [comment]
10/25 fixed.

**Comment by DoraKnst** [comment]
1029 checked,fixed
