### ISSUE TITLE
Test - 人員資料 - 新增/編輯 人員資料 - [就職狀態]選單移除"刪除"該選項

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#92]
**〔問題說明〕**
◆ Expect：
新增/編輯 人員資料 - [就職狀態]選單沒有"刪除"該選象

◆ Actual: 
新增/編輯 人員資料 - [就職狀態]選單 有"刪除"該選象(如下圖)
![image](https://user-images.githubusercontent.com/35495325/47488675-6874e800-d877-11e8-8111-7cf92aef525c.png)

**〔測試步驟〕**
登入ec_owner-ectest
進入 人員資料
新增人員資料 / 編輯人員資料
點[就職狀態]選單
選單中有[刪除]該選項

**〔功能/所在位置〕**
人員資料 - 新增/編輯

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 

**〔進案日期〕**
2018/10/25

**Comment by bcjohnblue** [comment]
10/25 fixed.

**Comment by DoraKnst** [comment]
1029 checked,fixed
