### ISSUE TITLE
Test - 人員資料 - 檢視[詳細人員資料] - 無上傳頭項圖示

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#93]
**〔問題說明〕**
◆ Expect：
若無上傳頭項
顯示如下圖
![image](https://user-images.githubusercontent.com/35495325/47491924-77ab6400-d87e-11e8-9445-d7411c5a4cc6.png)

◆ Actual: 
![image](https://user-images.githubusercontent.com/35495325/47491971-8d208e00-d87e-11e8-8d7f-c6a826352a6d.png)

**〔測試步驟〕**
登入ec_owner-ectest
進入 人員資料
檢視 "陳小明"的 詳細人員資料

**〔功能/所在位置〕**
員資料 - 檢視[詳細人員資料]

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 
已更新置白板，關鍵字查詢：issue#93

**〔進案日期〕**
2018/10/25

**Comment by bcjohnblue** [comment]
10/26 fixed.

**Comment by DoraKnst** [comment]
1029 checked,fixed
