### ISSUE TITLE
Test - 人員資料 - 檢視人員詳細資料 - 欄位名稱 調整為粗體

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#94]
**〔問題說明〕**
◆ Adjusted：
[檢視]人員詳細資料之介面：欄位名稱 調整為粗體
提升**欄位名稱**和**內容值**的區分程度 範例： **人員姓名** 皮卡丘
人員姓名→及這裡指稱的"欄位名稱"
請參考下圖 或白板
![image](https://user-images.githubusercontent.com/35495325/47540031-ba644f00-d905-11e8-9f5a-7bb3abffb77e.png)

◆ Actual: 
欄位名稱、內容值皆非粗體
![image](https://user-images.githubusercontent.com/35495325/47540097-0616f880-d906-11e8-93a6-3a71c9a3189f.png)

**〔測試步驟〕**
登入ec_owner-ectest
進入 人員資料
點任一筆人員資料的[詳細]
檢視人員詳細資料

**〔功能/所在位置〕**
人員資料 - 檢視人員詳細資料

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 
已更新置白板，關鍵字查詢：issue#94

**〔進案日期〕**
2018/10/26

**Comment by bcjohnblue** [comment]
10/26 fixed. 內容值已從粗體改為非粗體.

**Comment by DoraKnst** [comment]
1029 checked,fixed
