### ISSUE TITLE
Test - 人員資料 - 新增、編輯、檢視 人員資料 - 底色配色設定

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#96]
**〔問題說明〕**
◆ Expect：
和白板設置相同為 #F2F2F2

◆ Actual: 
和白板設置**不同**為 #ECF0F5

**〔測試步驟〕**
登入ec_owner-ectest
進入 人員資料
檢視 人員資料 / 編輯人員資料 底色

**〔功能/所在位置〕**
人員資料 

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 請參考白板色號設定

**〔進案日期〕**
 2018/10/26

**Comment by bcjohnblue** [comment]
10/26 fixed.

**Comment by DoraKnst** [comment]
1029 checked,fixed
