### ISSUE TITLE
Test - 人員資料 - 身分證字號&感應卡打卡功能 - 設定方式調整

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#97]
**〔問題說明〕**
◆ Adjusted：
透過就職狀態判斷是否[啟用 | 關閉]身分證字號&感應卡打卡功能
不提供[身分證字號功能開關]設定功能 (使用者自行設定開啟或關閉)

詳細設定說明請查看白板
"人員 身分證字號打卡功能&感應卡打卡功能  - 規則說明"

![image](https://user-images.githubusercontent.com/35495325/47549004-4ccc1900-d92d-11e8-9e75-c1bac26c6a1a.png)

◆ Current: 
提供身分證字號功能開關
在職、已離職、未到職、留職停薪>>皆可使用感應卡打卡

**〔功能/所在位置〕**
人員資料

**〔重要性〕**
★★★

**〔備註〕**
配合調整項目：
1. 新增單筆人員資料、編輯單筆人員資料：
若就職狀態為[在職]>>[身分證字號&感應卡打卡功能] - 顯示[開啟]
若就職狀態為[已離職、留職停薪、未到職]>>[身分證字號&感應卡打卡功能] - 顯示[關閉]

2. 檢視單筆人員資料
若就職狀態為[在職]>>[身分證字號&感應卡打卡功能] - 顯示[開啟]
若就職狀態為[已離職、留職停薪、未到職]>>[身分證字號&感應卡打卡功能] - 顯示[關閉]

3. 啟用、關閉 字體顏色色號請見白板

>已更新置白板，關鍵字查詢：issue#97

**〔進案日期〕**
2018/10/26

**Comment by bcjohnblue** [comment]
10/26 前端已調整.

**Comment by DoraKnst** [comment]
checked, fixed
