### ISSUE TITLE
Test - 人員資料 - 新增單筆人員資料、檢視詳細 - 欄位與內容無垂直置中對齊

### ISSUE THREAD

**Issue by DoraKnst** [DoraKnst/estatemanageplatform#99]
**〔問題說明〕**
◆ Expect：
新增單筆人員資料、檢視詳細單筆人員資料
所有題目欄位與內容欄位**有**垂直置中對齊
![image](https://user-images.githubusercontent.com/35495325/47692620-573e2980-dc31-11e8-92a0-6f7967a86b94.png)

◆ Actual: 
新增單筆人員資料、檢視詳細單筆人員資料
所有題目欄位與內容欄位**無**垂直置中對齊 (如下圖，檢視詳細也有相同狀況)
![image](https://user-images.githubusercontent.com/35495325/47692586-3aa1f180-dc31-11e8-8ecf-251d4ad38c36.png)

**〔測試步驟〕**
登入991122-testfield
進入人資料
檢視 水壺先生 人員資料 畫面
檢視 [編輯] 水壺先生 人員資料 畫面

**〔功能/所在位置〕**
 人員資料 - 新增單筆人員資料、檢視詳細

**〔重要性〕**
★★★

**〔備註〕**
@bcjohnblue 所有欄位
題目欄位：Ex. 姓名、通訊地址、工號
對應題目欄位
內容欄位：小紅帽、中泰路120號、S123456

**〔進案日期〕**
2018/10/30

**Comment by bcjohnblue** [comment]
10/30 fixed. 麻煩 @KnstMing 更版.

**Comment by KnstMing** [comment]
已上測試機，請驗測

**Comment by DoraKnst** [comment]
wanyuknst: checked,fixed
